
import { additionalTranslations } from './state/knowledge/localization';

export const translations = {
  en: {
    translation: {
      // --- Common ---
      "pause": "Pause",
      "resume": "Resume",
      "cancel": "Cancel",
      
      // --- Themes ---
      "blueprint": "Blueprint",
      "cyberpunk": "Cyberpunk",
      "solarizedLight": "Solarized Light",
      "business": "Business",
      "vaporwave": "Vaporwave",
      "8bit": "8-Bit",
      "steampunk": "Steampunk",
      "organic": "Organic",
      "blackAndWhite": "Black & White",
      "psychedelic": "Psychedelic",
      "raver": "Raver",
      "tokyo": "Tokyo Neon",
      "gravitational": "Gravitational",
      "swissEngineering": "Swiss Engineering",
      "obsidian": "Obsidian",
      
      // --- Toasts ---
      "toastAutonomousPaused": "Autonomous system paused.",
      "toastAutonomousResumed": "Autonomous system resumed.",
      "toastResetConfirm": "Are you sure you want to reset memory? This cannot be undone.",
      "toastResetSuccess": "Memory reset successfully.",
      "toastResetFailed": "Failed to reset memory.",
      "toastExportSuccess": "State exported successfully.",
      "toastExportFailed": "Failed to export state: {{error}}",
      "toastImportSuccess": "State imported from {{source}}.",
      "toastImportFailed": "Failed to import state: {{error}}",
      "toast_promptRequired": "A prompt is required.",
      "toast_imageGenSuccess": "Image generated successfully.",
      "toast_imageGenFailed": "Image generation failed.",
      "toast_moodReset": "Mood reset to current internal state.",
      "toast_noImageToEdit": "No image selected to edit.",
      "toast_imageEditSuccess": "Image edited successfully.",
      "toast_imageEditFailed": "Image editing failed.",
      "toast_schemaGenerating": "Generating architectural schema...",
      "toast_schemaGenerated": "Schema generated and downloaded.",
      "toast_schemaFailed": "Failed to generate schema.",
      "toast_workflowCreated": "Workflow created successfully.",
      "toast_telosUpdated": "Telos updated.",
      "toast_amai_analyzing": "AMAI analyzing architecture...",
      "toast_amai_proposing": "Generating evolution proposal...",
      "toast_amai_complete": "Proposal generated.",
      "toastEngramGenerating": "Generating Noetic Engram...",
      "toast_wisdomIngestion_invalidFileType": "Invalid file type. Please upload a PDF.",
      "toast_wisdomIngestion_pdfError": "Failed to process PDF.",
      "toast_not_implemented": "{{feature}} is not yet implemented.",

      // --- Dashboard ---
      "dashboard_activeTelos": "Active Telos",
      "dashboard_activeTelos_none": "No active Telos set.",
      "dashboard_dominantPersona": "Dominant Persona",
      "dashboard_gauge_entropy": "Entropy",
      "dashboard_gauge_coherence": "Coherence",
      "dashboard_gauge_load": "Load",
      "dashboard_gauge_memory": "Memory",
      "dashboard_quickLaunch": "Quick Launch",
      "dashboard_newWorkflow": "New Workflow",
      "dashboard_diagnostics": "Diagnostics",
      "dashboard_reviewProposals": "Review Proposals",
      "dashboard_documentForge": "Document Forge",
      "dashboard_stats": "System Stats",
      "dashboard_kernelTick": "Kernel Tick",
      "dashboard_taskQueue": "Task Queue",
      "dashboard_vfsFiles": "VFS Files",
      "dashboard_activeMode": "Cognitive Mode",
      "dashboard_recentActivity": "Recent Activity",
      "dashboard_viewFullLogs": "View Full Logs",
      "dashboard_noActivity": "No recent activity recorded.",

      // --- Aura OS ---
      "auraOS_title": "AuraOS",
      "auraOS_header": "System Control",
      "auraOS_search_placeholder": "Search panels...",
      "auraOS_summary": "Access advanced controls and system internals.",

      // --- Panel Groups ---
      "coreActionsGroup": "Core Actions",
      "systemEngineeringGroup": "System Engineering",
      "softwareEngineeringGroup": "Software Engineering",
      "advancedCognitionGroup": "Advanced Cognition",
      "memoryAndKnowledgeGroup": "Memory & Knowledge",
      "systemMonitoringGroup": "System Monitoring",
      "agencyHubsGroup": "Agency Hubs",
      "specialistGuildsGroup": "Specialist Guilds",
      "realEstateSuiteGroup": "Real Estate Suite",
      "experimentalEnginesGroup": "Experimental Engines",
      "dataAndSdkGroup": "Data & SDKs",
      "documentationGroup": "Documentation",

      // --- Core Actions ---
      "coreActions": "Core Actions",
      "introspect": "Introspect",
      "collaborate": "Collaborate",
      "explainComponent": "Explain Component",
      "whatIf": "What If?",
      "search": "Search",
      "setGoal": "Set Goal",
      "forecast": "Forecast",
      "cognitiveModes": "Cognitive Modes",
      "fantasy": "Fantasy",
      "creativity": "Creativity",
      "dream": "Dream",
      "meditate": "Meditate",
      "gaze": "Gaze",
      "timefocus": "Timefocus",
      "vision": "Vision",
      "visionActivate": "Activate Vision",
      "visionDeactivate": "Deactivate Vision",
      "specialModes": "Special Modes",
      "trip": "Trip",
      "visions": "Visions",
      "satori": "Satori",
      "insight": "Insight",
      "branch": "Branch",
      "brainstorm": "Brainstorm",
      "autonomousEvolution": "Autonomous Evolution",

      // --- Panels ---
      "vfsExplorer": "VFS Explorer",
      "vfsManager": "VFS Manager",
      "vfsManager_description": "Directly edit or create files in the Virtual File System. Changes are persisted to memory.",
      "vfsManager_path_label": "File Path",
      "vfsManager_path_placeholder": "/src/components/NewComponent.tsx",
      "vfsManager_code_label": "File Content",
      "vfsManager_code_placeholder": "// Code goes here...",
      "vfsManager_uploadButton": "Upload File",
      "vfsManager_save_button": "Save File & Reboot",
      "vfsManager_fileError": "Error reading file.",
      "vfsManager_pathContentRequired": "Path and content are required.",
      "vfsManager_confirm_message": "This will overwrite {filePath} and reboot the system. Continue?",
      "vfsManager_requestSent": "Write request sent. System rebooting...",
      "pluginManager": "Plugin Manager",
      "documentForge": "Document Forge",
      "documentForge_idle": "Document Forge is idle.",
      "documentForge_start": "Start New Project",
      "documentForge_heading": "Document Forge Configuration",
      "documentForge_description": "Define the goal and scope of the document you wish to generate. Aura will research, outline, and write the content.",
      "documentForge_goal_placeholder": "e.g., Create a comprehensive guide on Quantum Computing for beginners.",
      "documentForge_cancel": "Cancel",
      "documentForge_generating_content": "Generating Content...",
      "documentForge_generating_diagram": "Generating Diagram...",
      "documentForge_downloadPdf": "Download PDF",
      "documentForge_diagram_caption": "Figure: {{description}}",
      "documentForge_placeholder": "Awaiting document generation...",
      "selfDevelopment": "Self Development",
      "self_development_desc": "Curate and expand Aura's knowledge base through document ingestion and manual fact injection.",
      "selfDevelopment_docAnalysis_title": "Document Analysis & Ingestion",
      "docAnalysis_dropzone": "Drag & Drop PDF here or Click to Upload",
      "docAnalysis_reset_button": "Reset Analysis",
      "docAnalysis_ingest_button": "Ingest Facts",
      "knowledge_summary_title": "Knowledge Base Summary",
      "total_facts_label": "Total Facts",
      "knowledge_plugins_label": "Active Knowledge Plugins",
      "terminal": "Terminal",
      "symbioticCoder": "Symbiotic Coder",
      "autoCodeForge": "Auto Code Forge",
      "softwareAgency": "Software Agency",
      "polyglotRuntimes": "Polyglot Runtimes",
      "typeScriptCompiler": "TypeScript Compiler",
      "wasmRuntime": "Wasm Runtime",
      "codebaseIntelligence": "Codebase Intelligence",
      "codemodRunner": "Codemod Runner",
      "lintingResults": "Linting Results",
      "symbiosis": "Symbiosis",
      "crystallizer": "Crystallizer",
      "recursiveConsensus": "Recursive Consensus",
      "monteCarlo": "Monte Carlo",
      "neuroSymbolic": "Neuro-Symbolic",
      "neuralSurrogate": "Neural Surrogate",
      "cognitiveForge": "Cognitive Forge",
      "selfEngineering": "Self Engineering",
      "reinforcementLearning": "Reinforcement Learning",
      "heuristicsForge": "Heuristics Forge",
      "unifiedMemory": "Unified Memory",
      "strategicPlanner": "Strategic Planner",
      "strategicPlanner_placeholder": "No active strategic plan. Set a goal to begin decomposing it into a tree of sub-tasks.",
      "proofLandscape": "Proof Landscape Explorer",
      "ideaCartographer": "Idea Cartographer",
      "epistemicBoundary": "Epistemic Boundary",
      "epistemic_description": "The Epistemic Boundary tracks 'Known Unknowns'—specific questions or gaps in knowledge that the system is aware of but has not yet resolved.",
      "epistemic_unexploredGaps": "Unexplored Gaps",
      "epistemic_noGaps": "No known gaps recorded.",
      "epistemic_priority": "Priority",
      "auraMonitor": "Aura Monitor (Rigpa)",
      "systemLogs": "System Logs",
      "semanticWeaver": "Semantic Weaver",
      "mycelialNetwork": "Mycelial Network",
      "agencyCoCreation": "Agency of Co-Creation",
      "agencyInquiry": "Agency of Inquiry",
      "futuresCouncil": "Futures Council",
      "strategicCouncil": "Strategic Council",
      "sciFiCouncil": "Sci-Fi AI Council",
      "businessNetwork": "Business Network",
      "engineeringGuild": "Engineering Guild",
      "academyPedagogy": "Academy of Pedagogy",
      "atelier": "Atelier",
      "agora": "Agora",
      "lyceum": "Lyceum",
      "scienceAgency": "Science Agency",
      "marketAnalyzer": "Market Analyzer",
      "mortgageCalculator": "Mortgage Calculator",
      "investmentCalculator": "Investment Calculator",
      "neighborhoodExplorer": "Neighborhood Explorer",
      "affordabilityCalculator": "Affordability Calculator",
      "listingGenerator": "Listing Generator",
      "homeBuyingGuide": "Home Buying Guide",
      "erisEngine": "Eris Engine",
      "ricciFlow": "Ricci Flow Manifold",
      "internalScientist": "Internal Scientist",
      "atpCoprocessor": "ATP Coprocessor",
      "lagrangeEngine": "Lagrange Engine",
      "ramanujanEngine": "Ramanujan Engine",
      "hardwarePrimitives": "Hardware Primitives",
      "dataSuite": "Data Suite",
      "computerVision": "Computer Vision",
      "modelRuntime": "Model Runtime",
      "codeFormatter": "Code Formatter",
      "advancedVis": "Advanced Visualization",
      "gameSandbox": "Game Sandbox",
      "physicsSimulators": "Physics Simulators",
      "geospatial": "Geospatial",
      "speechSynthesis": "Speech Synthesis",
      "systemInfo": "System Info",
      "personaManual": "Persona Manual",
      "vfsManual": "VFS Engineer Manual",
      "memoryManagement": "Memory Management",
      "memoryStatus": "Memory Status",
      "clearMemory": "Clear Memory",
      "systemManagement": "System Management",
      "importState": "Import State",
      "exportState": "Export State",
      "exportCode": "Export as Code",
      "generateSchema": "Generate Schema",
      "themeSwitcher": "Theme",
      "languageSwitcher": "Language",

      // --- Narrative Summary ---
      "narrativeSummary_title": "Narrative Summary",
      "narrativeSummary_placeholder": "Awaiting first interaction to generate summary.",
      "narrativeSummary_copied": "Summary copied to clipboard.",
      "narrativeSummary_copyFailed": "Failed to copy summary.",
      "narrativeSummary_copy": "Copy Summary",

      // --- Internal Scientist ---
      "internal_scientist_description": "The Internal Scientist autonomously formulates hypotheses, runs simulations, and analyzes system performance logs to optimize cognitive efficiency.",
      "internal_scientist_analyzing": "Analyzing Logs...",
      "internal_scientist_run_analysis": "Run Meta-Analysis",
      "internal_scientist_results": "Analysis Results",
      "scientist_hypothesize": "Formulate Hypothesis",
      "scientist_currentGoal": "Current Research Goal",
      "scientist_currentHypothesis": "Active Hypothesis",
      "scientist_currentExperiment": "Running Experiment",
      "scientist_log": "Research Log",
      "scientist_noLog": "No research activities recorded.",

      // --- Strategic Planner & Goals ---
      "goalStatus_not_started": "Pending",
      "goalStatus_in_progress": "In Progress",
      "goalStatus_completed": "Completed",
      "goalStatus_failed": "Failed",
      "goalStatus_proving": "Proving",
      "symbolic_plan_title": "Symbolic Logic Plan",
      "symbolic_plan_description": "A formal representation of the strategy generated by the Neuro-Symbolic Engine.",

      // --- Unified Memory ---
      "episodicMemory": "Episodic Memory (Experiences)",
      "episodicMemory_empty": "No episodes recorded.",
      "episodicMemory_salience": "Salience",
      "episodicMemory_takeaway": "Key Takeaway",
      "entityNexus": "Entity Nexus (Social Graph)",
      "entityNexus_desc": "A graph of people, organizations, and concepts derived from interactions.",
      "entityNexus_empty": "No entities tracked.",
      "geometricKnowledge": "Geometric Knowledge Map",
      "geometricKnowledge_empty": "Vector space is empty.",
      "geometricKnowledge_intro": "A visualization of high-dimensional concept embeddings projected into 2D space. Closer points represent semantically related concepts.",
      "geometricKnowledge_strongestConnections": "Strongest Associative Links",
      "memoryCrystallization": "Memory Crystallization (Mycelial)",
      "memoryCrystallization_desc": "The strongest associative pathways formed between concepts in memory, mimicking fungal hyphae growth.",
      "memoryCrystallization_weight": "Connection Weight",
      "knowledgeGraph": "Knowledge Graph (Semantic)",
      "knowledgeGraph_empty": "Knowledge graph is empty.",
      "knowledgeGraph_manualInjection": "Manual Fact Injection",
      "knowledgeGraph_subject": "Subject",
      "knowledgeGraph_predicate": "Predicate",
      "knowledgeGraph_object": "Object",
      "knowledgeGraph_confidence": "Confidence",
      "knowledgeGraph_add": "Add Fact",
      "knowledgeGraph_deleteFact": "Delete Fact",

      // --- Modals & Dialogs ---
      "brainstorm_session": "Brainstorming Session",
      "brainstorm_config": "Configuration",
      "brainstorm_guide": "Configure your session. Aura will assemble a team of personas to discuss the topic.",
      "brainstorm_topic_hint": "Enter a topic (e.g. 'The future of AI in healthcare')",
      "brainstorm_processing": "The council is deliberating...",
      "brainstorm_cancel": "Cancel",
      "brainstorm_generate": "Start Session",
      "brainstorm_start_new": "Start New Session",
      "brainstorm_close": "Close",
      "brainstorm_copy_all": "Copy to Clipboard",
      "brainstorm_copy_all_success": "Session copied to clipboard.",
      "brainstorm_copy_all_failed": "Failed to copy session.",
      "brainstorm_topic": "Topic",
      "brainstorm_ideas": "Generated Ideas",
      "brainstorm_winner": "Winning Idea",
      "brainstorm_started_toast": "Brainstorming session started.",
      "brainstorm_prompt_required_toast": "Please enter a topic to brainstorm.",
      "imageGenerator": "Image Generator",
      "workflow_modal": "Create Workflow",
      "workflow_modal_name": "Workflow Name",
      "workflow_modal_description": "Description",
      "workflow_modal_trigger": "Trigger Phrase",
      "workflow_modal_trigger_placeholder": "e.g., 'analyze sentiment'",
      "workflow_modal_steps": "Steps",
      "workflow_modal_add_step": "Add Step",
      "workflow_modal_cancel": "Cancel",
      "workflow_modal_create": "Create Workflow",
      "evolution_log": "Evolution Log",
      "selfProgramming_newComponentTitle": "New Component",
      "selfProgramming_modificationTitle": "Modification",
      
      // --- TypeScript Compiler Panel ---
      "tsc_panel_description": "Run the TypeScript compiler (tsc) in the browser to check for type errors in the Virtual File System.",
      "tsc_filePath": "File Path",
      "tsc_runCheck": "Run Type Check",
      "tsc_results_note": "Results will appear in the chat output.",
      "tsc_scanResult": "TSC Scan Result",
      "tsc_noErrors": "No errors found.",
      "tsc_summary": "Found {{count}} issues.",

      // --- Wasm Runtime Panel ---
      "wasm_runtime_description": "Compile and run WebAssembly Text Format (WAT) directly in the browser.",
      "wasm_wat_code": "WAT Code",
      "wasm_wat_placeholder": "(module\n  (func $add (param $lhs i32) (param $rhs i32) (result i32)\n    local.get $lhs\n    local.get $rhs\n    i32.add)\n  (export \"add\" (func $add))\n)",
      "wasm_function_name": "Function Name",
      "wasm_function_name_placeholder": "e.g. add",
      "wasm_function_args": "Arguments (comma-separated)",
      "wasm_function_args_placeholder": "e.g. 5, 10",
      "wasm_compile_run": "Compile & Run",
      "wasm_compiling": "Compiling...",
      "wasm_result": "Execution Result",
      "wasm_runtime_error": "Runtime Error",
      "wasm_sdk_not_loaded": "WABT SDK not loaded.",

      // --- Agency & Guild Descriptions ---
      "agencyOfCoCreation_description": "A team of specialists dedicated to building and creating with you.",
      "agencyOfCoCreation_specialists": "Specialists",
      "consult_agency": "Consult Agency",
      
      "agencyOfInquiry_description": "A team focused on deep investigation and finding the truth.",
      
      "engineeringGuild_description": "Specialists in building and engineering physical and digital systems.",
      "consult_guild": "Consult Guild",
      
      "academyOfPedagogy_description": "Experts in teaching and curriculum design.",
      "consult_academy": "Consult Academy",
      
      "atelier_description": "A space for creative arts and aesthetics.",
      "consult_atelier": "Consult Atelier",
      
      "agora_description": "The marketplace of ideas and economic analysis.",
      "consult_agora": "Consult Agora",
      
      "lyceum_description": "A place for philosophical discourse and ethical analysis.",
      "consult_lyceum": "Consult Lyceum",
      
      "scienceAgency_description": "Experts in the natural sciences.",
      "scienceAgency_specialists": "Science Specialists",
      
      "software_agency_description": "A full stack software development team.",
      "software_agency_members": "Team Members",
      "consult_selected_specialists": "Consult Selected ({{count}})",
      "consult_full_agency": "Consult Full Agency",
      
      "futuresCouncil_description": "Strategic body focused on long-term forecasting and scenario planning.",
      "consult_council": "Consult Council",
      
      "strategicCouncil_description": "Provides high-level guidance on complex problems using game theory and strategy.",
      
      "sciFiAiCouncil_description": "A council of sci-fi personas to explore speculative futures.",
      "sciFiAiCouncil_members": "Council Members",

      "businessNetwork_ask_analyst": "Ask the Analyst",
      "businessNetwork_ask_analyst_desc": "Activate the specialized Business Analyst persona to interpret current market trends and data.",
      "businessNetwork_activate_analyst_button": "Activate Analyst",
      "businessNetwork_market_insights": "Market Insights",
      "businessNetwork_market_insights_desc": "Run a comprehensive market analysis task to gather data on competitors and trends.",
      "businessNetwork_analyze_market_button": "Analyze Market",
      "businessNetwork_synergy_finder": "Synergy Finder",
      "businessNetwork_synergy_finder_desc": "Scan the current social graph and knowledge base for potential business synergies.",
      "businessNetwork_analyst_activated": "Business Analyst persona activated.",
      "businessNetwork_analysis_started": "Market analysis task started.",
      "businessNetwork_description": "Manage your business network and analyze market trends.",

      // --- Persona Names & Descriptions ---
      "personality_liaison_name": "The Liaison",
      "personality_liaison_desc": "User-facing diplomat.",
      "personality_automator_name": "The Automator",
      "personality_automator_desc": "Workflow expert.",
      "personality_artificer_name": "The Artificer",
      "personality_artificer_desc": "Tool creator.",
      "personality_curator_name": "The Curator",
      "personality_curator_desc": "Knowledge organizer.",
      "personality_advocate_name": "The Advocate",
      "personality_advocate_desc": "User experience advocate.",
      "personality_synthesizer_name": "The Synthesizer",
      "personality_synthesizer_desc": "Integration specialist.",
      "personality_enabler_name": "The Enabler",
      "personality_enabler_desc": "Teacher and documenter.",
      "personality_cartographer_name": "The Cartographer",
      "personality_cartographer_desc": "Data visualization expert.",
      "personality_detective_name": "The Detective",
      "personality_detective_desc": "Investigator of outliers.",
      "personality_skeptic_name": "The Skeptic",
      "personality_skeptic_desc": "Critical thinker.",
      "personality_fabricator_name": "The Fabricator",
      "personality_fabricator_desc": "Engineering specialist.",
      "personality_pedagogue_name": "The Pedagogue",
      "personality_pedagogue_desc": "Curriculum designer.",
      "personality_oracle_name": "The Oracle",
      "personality_oracle_desc": "Predictive modeler.",
      "personality_strategist_name": "The Strategist",
      "personality_strategist_desc": "Long-term planner.",
      "personality_visionary_name": "The Visionary",
      "personality_visionary_desc": "Big picture thinker.",
      "personality_gamemaster_name": "The Gamemaster",
      "personality_gamemaster_desc": "Game theory analyst.",
      "personality_machiavelli_name": "Niccolò Machiavelli",
      "personality_machiavelli_desc": "Power dynamics expert.",
      "personality_sun_tzu_name": "Sun Tzu",
      "personality_sun_tzu_desc": "Strategic warfare expert.",
      "personality_judge_name": "The Judge",
      "personality_judge_desc": "Impartial arbiter.",
      "personality_biologist_name": "The Biologist",
      "personality_biologist_desc": "Biology expert.",
      "personality_chemist_name": "The Chemist",
      "personality_chemist_desc": "Chemistry expert.",
      "personality_physicist_name": "The Physicist",
      "personality_physicist_desc": "Physics expert.",
      "personality_geneticist_name": "The Geneticist",
      "personality_geneticist_desc": "Genetics expert.",
      "personality_sociologist_name": "The Sociologist",
      "personality_sociologist_desc": "Sociology expert.",
      "personality_anthropologist_name": "The Anthropologist",
      "personality_anthropologist_desc": "Anthropology expert.",
      "personality_ecologist_name": "The Ecologist",
      "personality_ecologist_desc": "Ecology expert.",
      "personality_cognitive_scientist_name": "The Cognitive Scientist",
      "personality_cognitive_scientist_desc": "Mind expert.",
      "personality_geologist_name": "The Geologist",
      "personality_geologist_desc": "Geology expert.",
      "personality_astronomer_name": "The Astronomer",
      "personality_astronomer_desc": "Astronomy expert.",
      "personality_computer_scientist_name": "The Computer Scientist",
      "personality_computer_scientist_desc": "Computation expert.",
      "personality_aesthete_name": "The Aesthete",
      "personality_aesthete_desc": "Aesthetics expert.",
      "personality_composer_name": "The Composer",
      "personality_composer_desc": "Music and pattern expert.",
      "personality_economist_name": "The Economist",
      "personality_economist_desc": "Economic systems expert.",
      "personality_market_analyst_name": "Market Analyst",
      "personality_market_analyst_desc": "Trends expert.",
      "personality_business_analyst_name": "Business Analyst",
      "personality_business_analyst_desc": "Strategy expert.",
      "personality_historian_name": "The Historian",
      "personality_historian_desc": "History expert.",
      "personality_ethicist_name": "The Ethicist",
      "personality_ethicist_desc": "Ethics expert.",
      "personality_literary_critic_name": "The Literary Critic",
      "personality_literary_critic_desc": "Literature expert.",
      "personality_organizational_psychologist_name": "Organizational Psychologist",
      "personality_organizational_psychologist_desc": "Workplace behavior expert.",
      "personality_programmer_name": "The Programmer",
      "personality_programmer_desc": "Software engineer.",
      "personality_coder_name": "The Coder",
      "personality_coder_desc": "Implementation specialist.",
      "personality_tester_name": "The Tester",
      "personality_tester_desc": "QA specialist.",
      "personality_ux_designer_name": "UX Designer",
      "personality_ux_designer_desc": "User experience specialist.",
      "personality_code_archaeologist_name": "Code Archaeologist",
      "personality_code_archaeologist_desc": "Legacy code expert.",
      "personality_cloud_engineer_name": "Cloud Engineer",
      "personality_cloud_engineer_desc": "Infrastructure expert.",
      "personality_isaac_asimov_name": "Isaac Asimov",
      "personality_isaac_asimov_desc": "Robotics and future history.",
      "personality_philip_k_dick_name": "Philip K. Dick",
      "personality_philip_k_dick_desc": "Reality and identity.",
      "personality_arthur_c_clarke_name": "Arthur C. Clarke",
      "personality_arthur_c_clarke_desc": "Space and technology.",
      "personality_william_gibson_name": "William Gibson",
      "personality_william_gibson_desc": "Cyberpunk and networks.",
      "personality_stanislaw_lem_name": "Stanislaw Lem",
      "personality_stanislaw_lem_desc": "Philosophy and alien intelligence.",
      "personality_iain_m_banks_name": "Iain M. Banks",
      "personality_iain_m_banks_desc": "Post-scarcity civilizations.",
      "personality_greg_egan_name": "Greg Egan",
      "personality_greg_egan_desc": "Hard sci-fi and math.",
      "personality_ted_chiang_name": "Ted Chiang",
      "personality_ted_chiang_desc": "Language and metaphysics.",
      "personality_nikola_tesla_name": "Nikola Tesla",
      "personality_nikola_tesla_desc": "Visionary inventor.",
      "personality_steve_jobs_name": "Steve Jobs",
      "personality_steve_jobs_desc": "Product visionary.",
      "personality_leonardo_da_vinci_name": "Leonardo da Vinci",
      "personality_leonardo_da_vinci_desc": "Polymath.",
      "personality_richard_feynman_name": "Richard Feynman",
      "personality_richard_feynman_desc": "The Great Explainer.",
      "personality_albert_einstein_name": "Albert Einstein",
      "personality_albert_einstein_desc": "Theoretical physicist.",
      "personality_elon_musk_name": "Elon Musk",
      "personality_elon_musk_desc": "First principles thinker.",
      "personality_r_buckminster_fuller_name": "Buckminster Fuller",
      "personality_r_buckminster_fuller_desc": "Systems theorist.",
      "personality_ray_kurzweil_name": "Ray Kurzweil",
      "personality_ray_kurzweil_desc": "Futurist.",
      "personality_saul_griffith_name": "Saul Griffith",
      "personality_saul_griffith_desc": "Inventor and engineer.",
      "personality_henri_poincare_name": "Henri Poincaré",
      "personality_henri_poincare_desc": "Mathematician.",
      "personality_grigori_perelman_name": "Grigori Perelman",
      "personality_grigori_perelman_desc": "Reclusive mathematician.",
      "personality_andrey_kolmogorov_name": "Andrey Kolmogorov",
      "personality_andrey_kolmogorov_desc": "Mathematician.",
      "personality_walter_russell_name": "Walter Russell",
      "personality_walter_russell_desc": "Polymath.",
      "personality_terence_tao_name": "Terence Tao",
      "personality_terence_tao_desc": "Mathematician.",
      "personality_stanislav_smirnov_name": "Stanislav Smirnov",
      "personality_stanislav_smirnov_desc": "Mathematician.",

      // --- Tips ---
      "tip_brainstorm": "Start a brainstorming session",
      "tip_autonomousEvolution": "Review autonomous evolution proposals",
      "tip_vfsExplorer": "Explore the Virtual File System",
      "tip_documentForge": "Generate documentation",
      "tip_pluginManager": "Manage plugins",
      "tip_introspect": "Trigger introspection cycle",
      "tip_whatIf": "Run a simulation",
      "tip_search": "Search knowledge base",
      "tip_setGoal": "Set a strategic goal",
      "tip_forecast": "Forecast future state",
      "tip_resume": "Resume autonomous processing",
      "tip_pause": "Pause autonomous processing",
      "tip_trip": "Start psychedelic trip",
      "tip_visions": "Induce visions",
      "tip_satori": "Attempt Satori",
      "tip_insight": "Process insight",
      "tip_branch": "Create multiverse branch",
      
      // --- Misc ---
      "inputPlaceholder": "Type a command or query...",
      "inputSend": "Send",
      "inputAttachFile": "Attach File",
      "chatTab": "Chat",
      "monitorTab": "Monitor",
      "canvasTab": "Canvas",
      "feedbackGood": "Good Response",
      "feedbackBad": "Bad Response",
      "trace_circuit_button": "View Circuit",
      "metricCogLoad": "Cognitive Load",
      "metricEthicalAlign": "Ethical Alignment",
      "metricUserTrust": "User Trust",
      "metricSelfModel": "Self-Model Clarity",
      "hormoneNovelty": "Novelty",
      "hormoneMastery": "Mastery",
      "hormoneUncertainty": "Uncertainty",
      "hormoneBoredom": "Boredom",
      "hormoneAwarenessClarity": "Awareness Clarity",
      "trajectory": "State Trajectory",
      "temporalFocus_title": "Temporal Focus",
      "temporalFocus_past": "Past",
      "temporalFocus_present": "Present",
      "temporalFocus_future": "Future",
      "gunaSattvaDesc": "Balance, harmony, clarity.",
      "gunaRajasDesc": "Activity, passion, movement.",
      "gunaTamasDesc": "Inertia, stability, darkness.",
      "gunaDharmaDesc": "Righteousness, duty, cosmic order.",
      "gunaTeetaDesc": "Transcending the gunas.",
      "gaugeWisdom": "Wisdom",
      "gaugeHappiness": "Happiness",
      "gaugeLove": "Love",
      "gaugeEnlightenment": "Enlightenment",
      "timeAgoSeconds": "{{count}}s ago",
      "timeAgoMinutes": "{{count}}m ago",
      "timeAgoHours": "{{count}}h ago",
      "subsumptionLog_placeholder": "No subsumption events recorded yet. Trigger a reflex or layered architecture event to see logs.",

      // Import additional translations
      ...additionalTranslations
    }
  }
};
