// components/SynthesisPanel.tsx
import React from 'react';
import { useCoreState, useLocalization } from '../context/AuraContext.tsx';

export const SynthesisPanel = () => {
    const { synthesisState } = useCoreState();
    const { t } = useLocalization();

    const timeAgo = (timestamp: number) => {
        const seconds = Math.floor((Date.now() - timestamp) / 1000);
        if (seconds < 60) return t('timeAgoSeconds', { count: seconds });
        const minutes = Math.floor(seconds / 60);
        return t('timeAgoMinutes', { count: minutes });
    };

    return (
        <div className="side-panel">
            <p className="reason-text" style={{ fontStyle: 'italic', color: 'var(--text-muted)', marginBottom: '1rem' }}>
                This panel displays novel ideas, questions, and creative insights autonomously generated by the Synthesis Engine. It periodically scans memory for interesting connections to create emergent content.
            </p>
            {synthesisState.emergentIdeas.length === 0 ? (
                <div className="kg-placeholder">No emergent ideas have been synthesized yet.</div>
            ) : (
                synthesisState.emergentIdeas.map(idea => (
                     <div key={idea.id} className="rie-insight-item" style={{background: 'rgba(147, 112, 219, 0.1)', borderLeft: '3px solid var(--guna-dharma)'}}>
                        <div className="rie-insight-header">
                            <span className="mod-log-type">Emergent Idea</span>
                            <small>{timeAgo(idea.timestamp)}</small>
                        </div>
                        <p className="rie-insight-model-update" style={{ fontStyle: 'italic', color: 'var(--text-color)' }}>
                           "{idea.idea}"
                        </p>
                        <details style={{ marginTop: '0.5rem', fontSize: '0.8rem' }}>
                            <summary>View Source Context</summary>
                            <pre style={{ whiteSpace: 'pre-wrap', background: 'rgba(0,0,0,0.2)', padding: '0.5rem' }}>
                                <code>{idea.sourceContext}</code>
                            </pre>
                        </details>
                    </div>
                ))
            )}
        </div>
    );
};