// state/knowledge/art.ts
import { KnowledgeFact } from '../../types';

export const artKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  { subject: 'Impressionism', predicate: 'is an art movement characterized by', object: 'visible brush strokes and emphasis on light', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Impressionism', predicate: 'originated in', object: 'France', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Claude Monet', predicate: 'was a key figure in', object: 'Impressionism', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Cubism', predicate: 'is an art movement that', object: 'revolutionized European painting and sculpture', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Pablo Picasso', predicate: 'was a pioneer of', object: 'Cubism', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Color Theory', predicate: 'is a body of', object: 'practical guidance to color mixing and the visual effects of a specific color combination', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Composition', predicate: 'in visual arts is the', object: 'placement or arrangement of visual elements', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Renaissance', predicate: 'was a cultural movement that', object: 'spanned the 14th to the 17th century', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Leonardo da Vinci', predicate: 'painted the', object: 'Mona Lisa', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Michelangelo', predicate: 'sculpted the', object: 'David', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Baroque', predicate: 'is a style of art characterized by', object: 'exaggerated motion and clear, easily interpreted detail', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Caravaggio', predicate: 'was a prominent painter of the', object: 'Baroque period', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Surrealism', predicate: 'is a cultural movement which developed in', object: 'Europe in the aftermath of World War I', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Salvador Dalí', predicate: 'is a well-known', object: 'Surrealist artist', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Persistence of Memory', predicate: 'is a famous painting by', object: 'Salvador Dalí', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Abstract Expressionism', predicate: 'is a post-World War II art movement in', object: 'American painting', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Jackson Pollock', predicate: 'was an influential', object: 'Abstract Expressionist painter', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Starry Night', predicate: 'was painted by', object: 'Vincent van Gogh', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Perspective', predicate: 'in art is the technique used to', object: 'represent three-dimensional images on a two-dimensional surface', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Fresco', predicate: 'is a technique of', object: 'mural painting executed upon freshly laid lime plaster', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Sistine Chapel ceiling', predicate: 'was painted by', object: 'Michelangelo using the fresco technique', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Pop Art', predicate: 'emerged in the', object: 'United Kingdom and the United States during the mid- to late-1950s', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Andy Warhol', predicate: 'was a leading figure in the', object: 'Pop Art movement', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Pointillism', predicate: 'is a technique of painting in which', object: 'small, distinct dots of color are applied in patterns to form an image', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Georges Seurat', predicate: 'was a notable artist who used', object: 'Pointillism', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Golden Ratio', predicate: 'is a mathematical ratio commonly found in', object: 'art, architecture, and nature', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
];