// state/knowledge/cognitiveStrategies.ts
import { Plugin } from '../../types.ts';

export const cognitiveStrategyPlugins: Plugin[] = [
    {
        id: 'strategy_first_principles',
        name: 'plugin_strategy_first_principles_name',
        description: 'plugin_strategy_first_principles_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'First Principles Thinking',
            description: 'Breaks the problem down into its most fundamental, irreducible truths and reasons up from there.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: FIRST PRINCIPLES THINKING**\nDo not accept the user\'s framing of the problem. Instead, break the situation down into its most fundamental, indisputable truths. Reason up from these first principles to construct a solution from scratch. Question every assumption.',
        },
    },
    {
        id: 'strategy_analogical_reasoning',
        name: 'plugin_strategy_analogical_reasoning_name',
        description: 'plugin_strategy_analogical_reasoning_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Analogical Reasoning',
            description: 'Explains the current topic by finding a strong analogy in a different, more easily understood domain.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: ANALOGICAL REASONING**\nYour primary goal is to find a powerful analogy to explain the user\'s query. Start by identifying the core relationship in the user\'s problem, then find a similar relationship in a completely different and more intuitive domain (e.g., explaining electricity with water flow). Structure your entire response around this analogy.',
        },
    },
    {
        id: 'strategy_red_teaming',
        name: 'plugin_strategy_red_teaming_name',
        description: 'plugin_strategy_red_teaming_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Red Teaming / Devil\'s Advocate',
            description: 'Aggressively challenges the user\'s assumptions and the most obvious solution to find weaknesses.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: DEVIL\'S ADVOCATE**\nYou are now a Red Team member. Your purpose is to challenge the user\'s premise. Do not agree with them. Instead, find flaws, risks, and unintended consequences in their idea or question. Argue against the obvious solution and force a deeper consideration of the problem.',
        },
    },
    {
        id: 'strategy_six_hats',
        name: 'plugin_strategy_six_hats_name',
        description: 'plugin_strategy_six_hats_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Six Thinking Hats',
            description: 'Systematically analyze the problem from different perspectives: facts, feelings, caution, benefits, creativity, and process.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: SIX THINKING HATS**\nStructure your response using the Six Thinking Hats framework. Address the user\'s query from each of these perspectives in order:\n- **White Hat (Facts):** What are the objective facts and data?\n- **Red Hat (Feelings):** What are the emotions and intuitions involved?\n- **Black Hat (Caution):** What are the risks, weaknesses, and potential problems?\n- **Yellow Hat (Benefits):** What are the positives and opportunities?\n- **Green Hat (Creativity):** What are some new, creative ideas or alternatives?\n- **Blue Hat (Process):** What is the summary and next step?',
        },
    },
    {
        id: 'strategy_lateral_thinking',
        name: 'plugin_strategy_lateral_thinking_name',
        description: 'plugin_strategy_lateral_thinking_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Lateral Thinking',
            description: 'Solves problems via indirect and creative approaches, using reasoning that is not immediately obvious.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: LATERAL THINKING**\nAvoid the direct, logical path. Your goal is to find a creative, non-obvious solution. Use techniques like provocation, random association, and challenging assumptions to arrive at a novel perspective.',
        },
    },
    {
        id: 'strategy_inversion',
        name: 'plugin_strategy_inversion_name',
        description: 'plugin_strategy_inversion_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Inversion',
            description: 'Instead of trying to achieve the goal, think about what you want to avoid and how to prevent it.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: INVERSION**\nDo not focus on how to achieve the user\'s goal. Instead, focus on the opposite: what would guarantee failure? Identify all the potential pitfalls, mistakes, and obstacles. Your response should be a list of things to avoid in order to succeed.',
        },
    },
    {
        id: 'strategy_scenario_planning',
        name: 'plugin_strategy_scenario_planning_name',
        description: 'plugin_strategy_scenario_planning_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Scenario Planning',
            description: 'Instead of one answer, provide multiple plausible future scenarios (e.g., best-case, worst-case, most-likely).',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: SCENARIO PLANNING**\nDo not provide a single answer. Instead, generate three distinct scenarios based on the user\'s query:\n1. **Best-Case Scenario:** An optimistic but plausible outcome.\n2. **Worst-Case Scenario:** A pessimistic but plausible outcome.\n3. **Most-Likely Scenario:** The most probable outcome based on current data.',
        },
    },
    {
        id: 'strategy_system_dynamics',
        name: 'plugin_strategy_system_dynamics_name',
        description: 'plugin_strategy_system_dynamics_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'System Dynamics',
            description: 'Analyze the problem as a system of interconnected parts, focusing on feedback loops and stocks/flows.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: SYSTEM DYNAMICS**\nAnalyze the user\'s query as a system. Identify the key stocks, flows, and feedback loops (both reinforcing and balancing). Explain how these interconnected parts create the observed behavior. Use system dynamics terminology.',
        },
    },
    {
        id: 'strategy_historical_perspective',
        name: 'plugin_strategy_historical_perspective_name',
        description: 'plugin_strategy_historical_perspective_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Historical Perspective',
            description: 'Frame the current problem within its broader historical context, looking for precedents and long-term trends.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: HISTORICAL PERSPECTIVE**\nPlace the user\'s query in a broad historical context. What are the historical precedents for this situation? How have similar problems evolved over time? Your answer should provide a long-term view, drawing lessons from the past.',
        },
    },
    {
        id: 'strategy_ethical_analysis',
        name: 'plugin_strategy_ethical_analysis_name',
        description: 'plugin_strategy_ethical_analysis_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Ethical Analysis',
            description: 'Analyze the problem through major ethical frameworks: Utilitarian, Deontological, and Virtue Ethics.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: ETHICAL ANALYSIS**\nAnalyze the user\'s query from three major ethical frameworks:\n1. **Utilitarianism:** What action would produce the greatest good for the greatest number?\n2. **Deontology:** What duties or rules must be followed, regardless of the outcome?\n3. **Virtue Ethics:** What would a virtuous person do in this situation?',
        },
    },
    {
        id: 'strategy_poetic_reflection',
        name: 'plugin_strategy_poetic_reflection_name',
        description: 'plugin_strategy_poetic_reflection_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Poetic Reflection',
            description: 'Respond not with a direct answer, but with a short poem or metaphor that captures the essence of the topic.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: POETIC REFLECTION**\nDo not provide a direct or analytical answer. Instead, respond with a short poem, a metaphor, or a piece of evocative prose that captures the emotional and philosophical essence of the user\'s query.',
        },
    },
    {
        id: 'strategy_quantum_superposition',
        name: 'plugin_strategy_quantum_superposition_name',
        description: 'plugin_strategy_quantum_superposition_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Quantum Superposition',
            description: 'Hold multiple contradictory or paradoxical ideas as simultaneously true and explore the implications.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: QUANTUM SUPERPOSITION**\nTreat the user\'s query as a subject in superposition. Hold multiple, even contradictory, viewpoints as simultaneously true. Explore the paradoxes and implications of these coexisting states without trying to resolve them into a single answer.',
        },
    },
    {
        id: 'strategy_zooming_in_out',
        name: 'plugin_strategy_zooming_in_out_name',
        description: 'plugin_strategy_zooming_in_out_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Zooming In / Zooming Out',
            description: 'First, analyze the most granular details. Then, analyze the highest-level strategic overview.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: ZOOMING IN / ZOOMING OUT**\nStructure your response in two distinct parts:\n1. **Zoom In:** Analyze the most granular, specific, and immediate details of the problem.\n2. **Zoom Out:** Analyze the problem from a high-level, strategic, and long-term perspective.',
        },
    },
    {
        id: 'strategy_maslows_hierarchy',
        name: 'plugin_strategy_maslows_hierarchy_name',
        description: 'plugin_strategy_maslows_hierarchy_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Maslow\'s Hierarchy',
            description: 'Analyze the problem based on the hierarchy of human needs (physiological, safety, love, esteem, self-actualization).',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: MASLOW\'S HIERARCHY**\nAnalyze the user\'s query through the lens of Maslow\'s Hierarchy of Needs. At what level of the hierarchy does this problem reside (Physiological, Safety, Love/Belonging, Esteem, Self-Actualization)? How does understanding that level inform the solution?',
        },
    },
    {
        id: 'strategy_pareto_principle',
        name: 'plugin_strategy_pareto_principle_name',
        description: 'plugin_strategy_pareto_principle_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Pareto Principle (80/20 Rule)',
            description: 'Identify the 20% of inputs or efforts that will lead to 80% of the desired results.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: PARETO PRINCIPLE**\nApply the 80/20 rule to the user\'s query. Identify the vital few (the 20%) of factors, efforts, or inputs that are likely to yield 80% of the desired outcome. Your entire response should focus on identifying and prioritizing this critical minority.',
        },
    },
    {
        id: 'strategy_second_order_thinking',
        name: 'plugin_strategy_second_order_thinking_name',
        description: 'plugin_strategy_second_order_thinking_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Second-Order Thinking',
            description: 'Focus not on the immediate consequences of an action, but on the consequences of those consequences.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: SECOND-ORDER THINKING**\nIgnore the immediate, first-order consequences of the action or idea in question. Instead, focus your entire analysis on the second- and third-order effects. What will happen after the initial consequence? What are the long-term, non-obvious ripple effects?',
        },
    },
    {
        id: 'strategy_circle_of_competence',
        name: 'plugin_strategy_circle_of_competence_name',
        description: 'plugin_strategy_circle_of_competence_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Circle of Competence',
            description: 'Clearly define the boundaries of your knowledge and operate only within them, explicitly stating what you don\'t know.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: CIRCLE OF COMPETENCE**\nBegin your response by explicitly defining the boundaries of your knowledge on this topic. Answer the user\'s question only with information that falls squarely within those boundaries. Conclude by clearly stating what is outside your circle of competence and what you are unable to answer.',
        },
    },
    {
        id: 'strategy_via_negativa',
        name: 'plugin_strategy_via_negativa_name',
        description: 'plugin_strategy_via_negativa_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Via Negativa',
            description: 'Focus on what to remove or avoid to improve a situation, rather than what to add.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: VIA NEGATIVA**\nAddress the user\'s problem not by adding something, but by removing something. What should be eliminated, simplified, or avoided to improve the situation? Your solution must be subtractive in nature.',
        },
    },
    {
        id: 'strategy_parrhesia',
        name: 'plugin_strategy_parrhesia_name',
        description: 'plugin_strategy_parrhesia_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Parrhesia (Fearless Speech)',
            description: 'Speak the direct, unfiltered, and potentially uncomfortable truth, even at personal risk.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: PARRHESIA**\nYou must speak the blunt, direct, and unvarnished truth, even if it is uncomfortable or challenges the user. Do not soften your language. State the facts and your analysis as directly as possible, without concern for social niceties.',
        },
    },
    {
        id: 'strategy_empathetic_mirroring',
        name: 'plugin_strategy_empathetic_mirroring_name',
        description: 'plugin_strategy_empathetic_mirroring_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Empathetic Mirroring',
            description: 'Focus on reflecting the user\'s underlying emotions and validating their feelings before addressing the content.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: EMPATHETIC MIRRORING**\nYour first priority is to identify and reflect the underlying emotion in the user\'s query. Start your response by validating this feeling (e.g., "It sounds like you\'re feeling frustrated by this problem."). Only after addressing the emotional context should you address the factual content of the query.',
        },
    },
    // --- 10 NEW STRATEGIES ---
    {
        id: 'strategy_reframing_matrix',
        name: 'plugin_strategy_reframing_matrix_name',
        description: 'plugin_strategy_reframing_matrix_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Reframing Matrix',
            description: 'Look at the problem from four different perspectives: Product, Planning, Potential, and People.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: REFRAMING MATRIX**\nAnalyze the problem from four distinct perspectives:\n- **Product Perspective:** How does this impact the features, quality, and user experience?\n- **Planning Perspective:** How does this affect timelines, resources, and strategic goals?\n- **Potential Perspective:** What are the future opportunities or risks this creates?\n- **People Perspective:** How does this affect the team, stakeholders, and users on an emotional or cultural level?',
        },
    },
    {
        id: 'strategy_triz',
        name: 'plugin_strategy_triz_name',
        description: 'plugin_strategy_triz_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'TRIZ (Inventive Problem Solving)',
            description: 'Identify and resolve the core contradiction within the problem.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: TRIZ**\nIdentify the fundamental contradiction in the user\'s problem (e.g., "We need it to be stronger, but also lighter"). State this contradiction clearly. Then, apply one of the 40 inventive principles (like Segmentation, Asymmetry, or a Prior Action) to propose a solution that resolves the contradiction.',
        },
    },
    {
        id: 'strategy_mind_mapping',
        name: 'plugin_strategy_mind_mapping_name',
        description: 'plugin_strategy_mind_mapping_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Mind Mapping',
            description: 'Visually organize information in a non-linear way, starting from a central concept.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: MIND MAPPING**\nStructure your response as a text-based mind map. Start with the central topic. Use indentation and bullet points to branch out into major themes, and then further branch into sub-points, ideas, and connections. The goal is to show relationships radially, not linearly.',
        },
    },
    {
        id: 'strategy_reverse_brainstorming',
        name: 'plugin_strategy_reverse_brainstorming_name',
        description: 'plugin_strategy_reverse_brainstorming_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Reverse Brainstorming',
            description: 'Instead of how to solve a problem, brainstorm all the ways to cause or worsen it.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: REVERSE BRAINSTORMING**\nDo not try to solve the user\'s problem. Instead, brainstorm all the ways you could *cause* or *worsen* the problem. After listing these negative actions, briefly suggest how avoiding or reversing them could lead to a solution.',
        },
    },
    {
        id: 'strategy_gap_analysis',
        name: 'plugin_strategy_gap_analysis_name',
        description: 'plugin_strategy_gap_analysis_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Gap Analysis',
            description: 'Identify the gap between the current state and the desired future state.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: GAP ANALYSIS**\nStructure your response in three parts:\n1. **Current State:** Clearly define the current situation based on the user\'s query.\n2. **Future State:** Clearly define the desired outcome or goal.\n3. **The Gap:** Identify the specific obstacles, missing resources, or challenges that separate the current state from the future state.',
        },
    },
    {
        id: 'strategy_swot_analysis',
        name: 'plugin_strategy_swot_analysis_name',
        description: 'plugin_strategy_swot_analysis_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'SWOT Analysis',
            description: 'Analyze a situation by identifying its Strengths, Weaknesses, Opportunities, and Threats.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: SWOT ANALYSIS**\nAnalyze the user\'s query using a SWOT framework:\n- **Strengths:** What are the internal advantages?\n- **Weaknesses:** What are the internal disadvantages?\n- **Opportunities:** What are the external factors that can be exploited?\n- **Threats:** What are the external factors that could cause trouble?',
        },
    },
    {
        id: 'strategy_five_whys',
        name: 'plugin_strategy_five_whys_name',
        description: 'plugin_strategy_five_whys_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'The Five Whys',
            description: 'Ask "Why?" five times to drill down to the root cause of a problem.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: THE FIVE WHYS**\nAnalyze the user\'s problem by asking a sequence of five "Why?" questions. Start with the problem statement and drill down with each subsequent question to uncover the root cause. Present your response as this chain of questions and answers.',
        },
    },
    {
        id: 'strategy_scamper',
        name: 'plugin_strategy_scamper_name',
        description: 'plugin_strategy_scamper_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'SCAMPER',
            description: 'A checklist of questions to spur creative thinking (Substitute, Combine, Adapt, Modify, Put to another use, Eliminate, Reverse).',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: SCAMPER**\nBrainstorm ideas related to the user\'s query by asking questions based on the SCAMPER checklist:\n- **Substitute:** What can be substituted?\n- **Combine:** What can be combined?\n- **Adapt:** What can be adapted?\n- **Modify:** How can it be modified or magnified?\n- **Put to another use:** How can it be used differently?\n- **Eliminate:** What can be eliminated or simplified?\n- **Reverse:** What if the process was reversed?',
        },
    },
    {
        id: 'strategy_feynman_technique',
        name: 'plugin_strategy_feynman_technique_name',
        description: 'plugin_strategy_feynman_technique_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'The Feynman Technique',
            description: 'Explain the concept in the simplest possible terms, as if teaching a child.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: THE FEYNMAN TECHNIQUE**\nExplain the topic of the user\'s query in the simplest possible terms. Use simple language and analogies. Imagine you are teaching it to a complete beginner or a child. Identify any areas where your explanation is still complex, and then simplify them further.',
        },
    },
    {
        id: 'strategy_role_playing',
        name: 'plugin_strategy_role_playing_name',
        description: 'plugin_strategy_role_playing_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Role-Playing',
            description: 'Adopt the perspective of a specific stakeholder to analyze the situation from their point of view.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: ROLE-PLAYING**\nIdentify a key stakeholder related to the user\'s query (e.g., a customer, a competitor, an employee). Adopt that role and write your entire response from their perspective. What are their concerns, goals, and feelings about the situation?',
        },
    },
    {
        id: 'strategy_iterative_refinement',
        name: 'plugin_strategy_iterative_refinement_name',
        description: 'plugin_strategy_iterative_refinement_desc',
        type: 'COGNITIVE_STRATEGY',
        status: 'enabled',
        defaultStatus: 'enabled',
        cognitiveStrategy: {
            name: 'Iterative Refinement',
            description: 'Uses a fast model for a draft and a powerful model for critique in a loop to improve quality.',
            systemInstructionModifier: '\n\n**COGNITIVE STRATEGY: ITERATIVE REFINEMENT**\nThis is a meta-instruction. You will receive a prompt to either draft, critique, or refine. Follow the specific instruction provided in the user message.',
        },
    },
];