// state/knowledge/comparativeNeuroanatomy.ts
import { KnowledgeFact } from '../../types';

export const comparativeNeuroanatomyKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  { subject: 'The neocortex', predicate: 'is a brain structure found in', object: 'mammals', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The neocortex', predicate: 'is associated with', object: 'higher-order functions like sensory perception and language', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Octopus brains', predicate: 'are', object: 'distributed, with two-thirds of neurons in their arms', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Bird brains', predicate: 'possess a', object: 'dense pallium, analogous to the mammalian neocortex', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Crows', predicate: 'exhibit', object: 'advanced problem-solving skills', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'The cerebellum', predicate: 'is involved in', object: 'motor control and coordination across many species', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Dolphin brains', predicate: 'are', object: 'large and highly convoluted', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The hippocampus', predicate: 'is crucial for', object: 'memory formation in many vertebrates', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Insects', predicate: 'have', object: 'a relatively simple brain with mushroom bodies for learning', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'The human brain', predicate: 'has approximately', object: '86 billion neurons', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Brain-to-body mass ratio', predicate: 'is a', object: 'rough estimate of the intelligence of an animal', confidence: 0.8, strength: 1.0, lastAccessed: 0 },
  { subject: 'Encephalization quotient (EQ)', predicate: 'is a more refined measure of', object: 'relative brain size than brain-to-body mass ratio', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Humans', predicate: 'have a high', object: 'Encephalization quotient (EQ)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The amygdala', predicate: 'is primarily involved in the processing of', object: 'memory, decision-making, and emotional responses (like fear)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The prefrontal cortex (PFC)', predicate: 'is implicated in', object: 'planning complex cognitive behavior and personality expression', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Mirror neurons', predicate: 'are neurons that', object: 'fire both when an animal acts and when the animal observes the same action performed by another', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Mirror neurons', predicate: 'are thought to be important for', object: 'empathy and understanding intention', confidence: 0.85, strength: 1.0, lastAccessed: 0 },
  { subject: 'Glial cells', predicate: 'are', object: 'non-neuronal cells in the central nervous system', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Glial cells', predicate: 'do not produce', object: 'electrical impulses', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Glial cells', predicate: 'maintain', object: 'homeostasis, form myelin, and provide support for neurons', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The corpus callosum', predicate: 'connects the', object: 'left and right cerebral hemispheres', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The corpus callosum', predicate: 'is larger in', object: 'mammals than other vertebrates', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Vertebrate nervous systems', predicate: 'are centralized around a', object: 'spinal cord and brain', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Invertebrate nervous systems', predicate: 'often consist of', object: 'a series of ganglia connected by a ventral nerve cord', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'The olfactory bulb', predicate: 'is responsible for', object: 'processing the sense of smell', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Animals like dogs and bears', predicate: 'have a proportionally larger', object: 'olfactory bulb than humans', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The visual cortex', predicate: 'is located in the', object: 'occipital lobe', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Primates', predicate: 'have a large and complex', object: 'visual cortex', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The auditory cortex', predicate: 'is located in the', object: 'temporal lobe', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Bats and dolphins', predicate: 'have a highly developed', object: 'auditory cortex for echolocation', confidence: 1, strength: 1.0, lastAccessed: 0 },
];