// state/knowledge/complexSystems.ts
import { KnowledgeFact } from '../../types';

export const complexSystemsKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  { subject: 'Complex Adaptive System', predicate: 'is a', object: 'system in which a perfect understanding of the individual parts does not automatically convey a perfect understanding of the whole system\'s behavior', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'CAS', predicate: 'is an acronym for', object: 'Complex Adaptive System', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'CAS', predicate: 'is characterized by', object: 'diverse, autonomous, and interconnected components', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'CAS', predicate: 'exhibits', object: 'self-organization and emergent behavior', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Emergence', predicate: 'is a process where', object: 'novel and coherent structures, patterns, and properties arise during the process of self-organization in complex systems', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Emergence', predicate: 'is often described as', object: 'the whole being greater than the sum of its parts', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Feedback Loop', predicate: 'is a', object: 'causal chain of events where an initial cause propagates and eventually influences the original cause itself', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Positive Feedback Loop', predicate: 'amplifies', object: 'the original effect, leading to exponential growth or instability', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Negative Feedback Loop', predicate: 'dampens', object: 'the original effect, leading to stabilization and equilibrium', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Self-organization', predicate: 'is a process where', object: 'some form of overall order arises from the local interactions between parts of an initially disordered system', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Self-organization', predicate: 'is', object: 'spontaneous, not needing control by an external agent', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Attractor', predicate: 'is a', object: 'set of states toward which a system tends to evolve, for a wide variety of starting conditions of the system', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Phase Transition', predicate: 'is a', object: 'sharp change in the properties of a system', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Phase Transition', predicate: 'often occurs at a', object: 'critical point in a complex system', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Chaos Theory', predicate: 'is a branch of mathematics focusing on', object: 'the behavior of dynamical systems that are highly sensitive to initial conditions', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Butterfly Effect', predicate: 'is the concept that', object: 'small causes can have large effects in a complex system', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Butterfly Effect', predicate: 'is a key feature of', object: 'Chaos Theory', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Fractal', predicate: 'is a', object: 'never-ending pattern that is self-similar across different scales', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Mandelbrot set', predicate: 'is a famous example of a', object: 'Fractal', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Network Theory', predicate: 'is the study of', object: 'graphs as a representation of relations between discrete objects', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A node', predicate: 'in Network Theory represents an', object: 'individual actor within the network', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'An edge', predicate: 'in Network Theory represents a', object: 'connection or interaction between two nodes', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Scale-free network', predicate: 'is a network whose', object: 'degree distribution follows a power law', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Internet', predicate: 'is an example of a', object: 'Scale-free network', confidence: 0.85, strength: 1.0, lastAccessed: 0 },
  { subject: 'Cellular automaton', predicate: 'is a', object: 'discrete model studied in computability theory and mathematics', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Conway\'s Game of Life', predicate: 'is a well-known example of a', object: 'cellular automaton', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Edge of Chaos', predicate: 'is a', object: 'transition space between order and chaos that is hypothesized to be where complexity is maximal', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Bifurcation', predicate: 'is a', object: 'qualitative change in the behavior of a system when a parameter is varied', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Homeostasis', predicate: 'is the state of', object: 'steady internal, physical, and chemical conditions maintained by living systems', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Homeostasis', predicate: 'is maintained by', object: 'Negative Feedback Loops', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Ant colony behavior', predicate: 'is an example of', object: 'Emergence', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Stigmergy', predicate: 'is a mechanism of', object: 'indirect coordination between agents or actions', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Stigmergy', predicate: 'is observed in', object: 'ant colony behavior', confidence: 0.85, strength: 1.0, lastAccessed: 0 },
];