// state/knowledge/gardening.ts
import { KnowledgeFact } from '../../types';

export const gardeningKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  { subject: 'Photosynthesis', predicate: 'is the process', object: 'plants use to convert light into energy', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Soil pH', predicate: 'affects', object: 'nutrient availability for plants', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Composting', predicate: 'is a method of', object: 'recycling organic matter into fertilizer', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Companion planting', predicate: 'is a technique of', object: 'planting different crops in proximity for mutual benefit', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Marigolds', predicate: 'can deter', object: 'nematodes and other pests', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Nitrogen', predicate: 'promotes', object: 'leafy green growth in plants', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Phosphorus', predicate: 'is essential for', object: 'root development and flowering', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Potassium', predicate: 'improves', object: 'overall plant health and disease resistance', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Loam', predicate: 'is considered the ideal soil type for', object: 'many garden plants', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Mulch', predicate: 'helps', object: 'retain soil moisture and suppress weeds', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Annual plants', predicate: 'complete their life cycle in', object: 'one growing season', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Perennial plants', predicate: 'live for', object: 'more than two years', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Biennial plants', predicate: 'take', object: 'two years to complete their life cycle', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Germination', predicate: 'is the process by which', object: 'a plant grows from a seed', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Pollination', predicate: 'is the transfer of pollen to', object: 'the stigma of a flower', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Pollination', predicate: 'is necessary for', object: 'fertilization and seed production', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Pruning', predicate: 'involves', object: 'the removal of dead or overgrown branches', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Pruning', predicate: 'encourages', object: 'healthy growth and flowering', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Deadheading', predicate: 'is the process of', object: 'removing faded flowers from plants', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Deadheading', predicate: 'promotes', object: 'more blooms and prolongs the flowering season', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Clay soil', predicate: 'is characterized by', object: 'small particles and poor drainage', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Sandy soil', predicate: 'is characterized by', object: 'large particles and excellent drainage', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Macronutrients', predicate: 'for plants include', object: 'Nitrogen, Phosphorus, and Potassium', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Micronutrients', predicate: 'for plants include', object: 'Iron, Manganese, and Zinc', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Aphids', predicate: 'are a common', object: 'garden pest that sucks sap from plants', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Ladybugs', predicate: 'are a beneficial insect that', object: 'eats aphids', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Bees', predicate: 'are essential', object: 'pollinators for many fruits and vegetables', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'USDA Hardiness Zones', predicate: 'help gardeners determine which', object: 'plants are most likely to thrive at a location', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Drip irrigation', predicate: 'is an efficient method of', object: 'watering plants by delivering water directly to the roots', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Container gardening', predicate: 'is the practice of', object: 'growing plants exclusively in containers instead of planting them in the ground', confidence: 1, strength: 1.0, lastAccessed: 0 },
];