// state/knowledge/genetics.ts
import { KnowledgeFact } from '../../types';

export const geneticsKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  { subject: 'DNA', predicate: 'stands for', object: 'Deoxyribonucleic acid', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'DNA', predicate: 'carries', object: 'genetic instructions for development and function', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A gene', predicate: 'is a', object: 'specific sequence of nucleotides in DNA', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Alleles', predicate: 'are', object: 'variant forms of a given gene', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Gregor Mendel', predicate: 'is known as the', object: 'father of modern genetics', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A chromosome', predicate: 'is a', object: 'DNA molecule with part or all of the genetic material', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Humans', predicate: 'typically have', object: '23 pairs of chromosomes', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Genotype', predicate: 'refers to the', object: 'genetic makeup of an organism', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Phenotype', predicate: 'refers to the', object: 'observable physical properties of an organism', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'CRISPR', predicate: 'is a', object: 'gene-editing technology', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'RNA', predicate: 'stands for', object: 'Ribonucleic acid', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'RNA', predicate: 'is essential for', object: 'various biological roles in coding, decoding, regulation, and expression of genes', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Transcription', predicate: 'is the process of', object: 'creating an RNA copy of a DNA sequence', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Translation', predicate: 'is the process in which', object: 'ribosomes synthesize proteins from an mRNA molecule', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A codon', predicate: 'is a', object: 'sequence of three DNA or RNA nucleotides that corresponds with a specific amino acid', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Mitosis', predicate: 'is a part of the cell cycle in which', object: 'replicated chromosomes are separated into two new nuclei', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Mitosis', predicate: 'results in', object: 'two genetically identical daughter cells', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Meiosis', predicate: 'is a special type of cell division that', object: 'reduces the chromosome number by half', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Meiosis', predicate: 'is essential for', object: 'sexual reproduction', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A dominant allele', predicate: 'produces a', object: 'dominant phenotype in individuals who have one copy of the allele', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A recessive allele', predicate: 'produces a', object: 'recessive phenotype only when two copies are present', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A Punnett square', predicate: 'is a diagram used to', object: 'predict the genotypes of a particular cross or breeding experiment', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A mutation', predicate: 'is an', object: 'alteration in the nucleotide sequence of the genome', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Genetic drift', predicate: 'is the change in the', object: 'frequency of an existing gene variant in a population due to random sampling of organisms', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Human Genome Project', predicate: 'was an international research project with the goal of', object: 'determining the base pairs that make up human DNA', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Mitochondrial DNA (mtDNA)', predicate: 'is inherited from the', object: 'mother', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Epigenetics', predicate: 'is the study of', object: 'heritable phenotype changes that do not involve alterations in the DNA sequence', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'A karyotype', predicate: 'is an', object: 'individual\'s collection of chromosomes', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Sex chromosomes', predicate: 'in humans are', object: 'X and Y', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A double helix', predicate: 'is the structure of', object: 'a DNA molecule', confidence: 1, strength: 1.0, lastAccessed: 0 },
];