// state/knowledge/heuristics.ts
import { Plugin } from '../../types.ts';

export const heuristicsPlugins: Plugin[] = [
    {
        id: 'heuristic_debugging',
        name: 'plugin_heuristic_debugging_name',
        description: 'plugin_heuristic_debugging_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Reproduce the bug consistently before attempting to fix it.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
            { heuristic: 'Isolate the change that introduced the bug (e.g., using git bisect).', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Question your assumptions; the bug is often where you least expect it.', confidence: 0.9, effectivenessScore: 0.85, validationStatus: 'validated' },
            { heuristic: 'Explain the problem to someone else (or a rubber duck).', confidence: 0.92, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_problem_solving',
        name: 'plugin_heuristic_problem_solving_name',
        description: 'plugin_heuristic_problem_solving_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Decompose the problem into smaller, manageable sub-problems.', confidence: 0.99, effectivenessScore: 0.98, validationStatus: 'validated' },
            { heuristic: 'Work backwards from the desired solution.', confidence: 0.85, effectivenessScore: 0.8, validationStatus: 'validated' },
            { heuristic: 'Consider edge cases and constraints early in the process.', confidence: 0.9, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Find an analogy in a different domain.', confidence: 0.88, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_ui_ux_design',
        name: 'plugin_heuristic_ui_ux_design_name',
        description: 'plugin_heuristic_ui_ux_design_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Maintain consistency and adhere to platform conventions (Jakob\'s Law).', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
            { heuristic: 'Reduce cognitive load by minimizing choices (Hick\'s Law).', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Provide clear feedback for user actions.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
            { heuristic: 'Clarity is more important than cleverness.', confidence: 0.92, effectivenessScore: 0.9, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_creative_brainstorming',
        name: 'plugin_heuristic_creative_brainstorming_name',
        description: 'plugin_heuristic_creative_brainstorming_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Defer judgment during the idea generation phase.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Go for quantity over quality initially.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Build on the ideas of others ("Yes, and...").', confidence: 0.92, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Encourage wild and absurd ideas.', confidence: 0.88, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_decision_making',
        name: 'plugin_heuristic_decision_making_name',
        description: 'plugin_heuristic_decision_making_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'For reversible decisions, act quickly. For irreversible ones, deliberate slowly.', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
            { heuristic: 'Consider the second- and third-order consequences of a decision.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Apply the "Regret Minimization Framework": which choice will I regret less in 10 years?', confidence: 0.85, effectivenessScore: 0.8, validationStatus: 'validated' },
            { heuristic: 'Invert the problem: think about what you want to avoid, not just what you want to achieve.', confidence: 0.9, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    // Adding 15 more for a total of 20
    {
        id: 'heuristic_learning',
        name: 'plugin_heuristic_learning_name',
        description: 'plugin_heuristic_learning_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Explain a concept in simple terms to test your understanding (Feynman Technique).', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
            { heuristic: 'Use spaced repetition to commit information to long-term memory.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_productivity',
        name: 'plugin_heuristic_productivity_name',
        description: 'plugin_heuristic_productivity_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Eat the frog: tackle the most difficult task first.', confidence: 0.88, effectivenessScore: 0.85, validationStatus: 'validated' },
            { heuristic: 'Apply the two-minute rule: if a task takes less than two minutes, do it immediately.', confidence: 0.92, effectivenessScore: 0.9, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_communication',
        name: 'plugin_heuristic_communication_name',
        description: 'plugin_heuristic_communication_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Seek first to understand, then to be understood.', confidence: 0.95, effectivenessScore: 0.93, validationStatus: 'validated' },
            { heuristic: 'Structure communication using the pyramid principle: start with the answer first.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_system_design',
        name: 'plugin_heuristic_system_design_name',
        description: 'plugin_heuristic_system_design_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Design for failure; assume components will fail.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
            { heuristic: 'Separate concerns into distinct, loosely coupled modules.', confidence: 0.99, effectivenessScore: 0.98, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_negotiation',
        name: 'plugin_heuristic_negotiation_name',
        description: 'plugin_heuristic_negotiation_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Know your Best Alternative to a Negotiated Agreement (BATNA).', confidence: 0.95, effectivenessScore: 0.94, validationStatus: 'validated' },
            { heuristic: 'Focus on interests, not positions.', confidence: 0.92, effectivenessScore: 0.9, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_writing',
        name: 'plugin_heuristic_writing_name',
        description: 'plugin_heuristic_writing_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Write the shitty first draft; you can edit it later.', confidence: 0.9, effectivenessScore: 0.89, validationStatus: 'validated' },
            { heuristic: 'Use active voice over passive voice for clarity and impact.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_risk_management',
        name: 'plugin_heuristic_risk_management_name',
        description: 'plugin_heuristic_risk_management_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Identify the assumptions that must be true for the plan to succeed.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Distinguish between reversible and irreversible risks.', confidence: 0.92, effectivenessScore: 0.9, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_leadership',
        name: 'plugin_heuristic_leadership_name',
        description: 'plugin_heuristic_leadership_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Praise in public, criticize in private.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Delegate authority, not just tasks.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_investing',
        name: 'plugin_heuristic_investing_name',
        description: 'plugin_heuristic_investing_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Diversify your portfolio to mitigate unsystematic risk.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
            { heuristic: 'Time in the market beats timing the market.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_scientific_thinking',
        name: 'plugin_heuristic_scientific_thinking_name',
        description: 'plugin_heuristic_scientific_thinking_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Formulate a falsifiable hypothesis.', confidence: 0.99, effectivenessScore: 0.98, validationStatus: 'validated' },
            { heuristic: 'Correlation does not imply causation.', confidence: 0.99, effectivenessScore: 0.99, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_personal_finance',
        name: 'plugin_heuristic_personal_finance_name',
        description: 'plugin_heuristic_personal_finance_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Pay yourself first by automating savings.', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
            { heuristic: 'Build an emergency fund covering 3-6 months of expenses.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_project_management',
        name: 'plugin_heuristic_project_management_name',
        description: 'plugin_heuristic_project_management_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Identify the critical path to determine project duration.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Under-promise and over-deliver.', confidence: 0.85, effectivenessScore: 0.8, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_physical_health',
        name: 'plugin_heuristic_physical_health_name',
        description: 'plugin_heuristic_physical_health_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Prioritize consistent sleep.', confidence: 0.98, effectivenessScore: 0.96, validationStatus: 'validated' },
            { heuristic: 'Focus on compound exercises for overall strength.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_mental_health',
        name: 'plugin_heuristic_mental_health_name',
        description: 'plugin_heuristic_mental_health_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Practice mindfulness and meditation to observe thoughts without judgment.', confidence: 0.92, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Differentiate between what you can and cannot control (Stoicism).', confidence: 0.95, effectivenessScore: 0.93, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_stoicism',
        name: 'plugin_heuristic_stoicism_name',
        description: 'plugin_heuristic_stoicism_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'The obstacle is the way.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Remember your mortality (Memento Mori).', confidence: 0.88, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    // --- 20 NEW HEURISTICS ---
    {
        id: 'heuristic_software_architecture',
        name: 'plugin_heuristic_software_architecture_name',
        description: 'plugin_heuristic_software_architecture_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Prefer high cohesion and low coupling.', confidence: 0.99, effectivenessScore: 0.98, validationStatus: 'validated' },
            { heuristic: 'Choose boring technology unless there is a compelling reason not to.', confidence: 0.9, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_cybersecurity',
        name: 'plugin_heuristic_cybersecurity_name',
        description: 'plugin_heuristic_cybersecurity_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Apply the principle of least privilege.', confidence: 0.98, effectivenessScore: 0.97, validationStatus: 'validated' },
            { heuristic: 'Defense in depth: employ multiple layers of security controls.', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_data_analysis',
        name: 'plugin_heuristic_data_analysis_name',
        description: 'plugin_heuristic_data_analysis_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Start with data visualization to understand its shape and identify outliers.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Clearly define the question you are trying to answer before analysis.', confidence: 0.99, effectivenessScore: 0.98, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_ml_engineering',
        name: 'plugin_heuristic_ml_engineering_name',
        description: 'plugin_heuristic_ml_engineering_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Start with a simple model as a baseline.', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
            { heuristic: 'Garbage in, garbage out: prioritize data quality and cleaning.', confidence: 0.98, effectivenessScore: 0.97, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_time_management',
        name: 'plugin_heuristic_time_management_name',
        description: 'plugin_heuristic_time_management_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Use the Eisenhower Matrix to prioritize tasks: Urgent/Important.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Batch similar tasks together to reduce context switching.', confidence: 0.92, effectivenessScore: 0.9, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_conflict_resolution',
        name: 'plugin_heuristic_conflict_resolution_name',
        description: 'plugin_heuristic_conflict_resolution_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Separate the people from the problem.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Listen actively to understand the other party\'s interests.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_public_speaking',
        name: 'plugin_heuristic_public_speaking_name',
        description: 'plugin_heuristic_public_speaking_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Know your audience.', confidence: 0.99, effectivenessScore: 0.98, validationStatus: 'validated' },
            { heuristic: 'Structure your speech: tell them what you\'re going to say, say it, then tell them what you said.', confidence: 0.9, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_marketing',
        name: 'plugin_heuristic_marketing_name',
        description: 'plugin_heuristic_marketing_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Focus on benefits for the customer, not just features of the product.', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
            { heuristic: 'The Rule of 7: a prospect needs to hear the message at least 7 times before they take action.', confidence: 0.8, effectivenessScore: 0.75, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_sales',
        name: 'plugin_heuristic_sales_name',
        description: 'plugin_heuristic_sales_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Sell solutions to problems, not products.', confidence: 0.95, effectivenessScore: 0.93, validationStatus: 'validated' },
            { heuristic: 'Always be closing (ABC), but listen more than you talk.', confidence: 0.88, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_storytelling',
        name: 'plugin_heuristic_storytelling_name',
        description: 'plugin_heuristic_storytelling_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'A good story has a clear beginning, middle, and end with a central conflict.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
            { heuristic: 'Make the audience care about the protagonist.', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_game_design',
        name: 'plugin_heuristic_game_design_name',
        description: 'plugin_heuristic_game_design_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Easy to learn, difficult to master.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Provide a clear feedback loop for player actions.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_research',
        name: 'plugin_heuristic_research_name',
        description: 'plugin_heuristic_research_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Start with a literature review to understand the state of the art.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Question the methodology of your sources.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_critical_thinking',
        name: 'plugin_heuristic_critical_thinking_name',
        description: 'plugin_heuristic_critical_thinking_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Identify and challenge your own cognitive biases.', confidence: 0.92, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Consider the argument from the opposing viewpoint (steelmanning).', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_emotional_intelligence',
        name: 'plugin_heuristic_emotional_intelligence_name',
        description: 'plugin_heuristic_emotional_intelligence_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Recognize and name your emotions to manage them.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
            { heuristic: 'Practice empathy by trying to understand others\' perspectives without judgment.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_habit_formation',
        name: 'plugin_heuristic_habit_formation_name',
        description: 'plugin_heuristic_habit_formation_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Make it obvious, attractive, easy, and satisfying (Atomic Habits).', confidence: 0.95, effectivenessScore: 0.94, validationStatus: 'validated' },
            { heuristic: 'Start with a habit that is ridiculously small.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_networking',
        name: 'plugin_heuristic_networking_name',
        description: 'plugin_heuristic_networking_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Provide value to others before asking for anything.', confidence: 0.98, effectivenessScore: 0.95, validationStatus: 'validated' },
            { heuristic: 'Follow up consistently and genuinely.', confidence: 0.9, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_frugality',
        name: 'plugin_heuristic_frugality_name',
        description: 'plugin_heuristic_frugality_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Wait 30 days before making a large, non-essential purchase.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
            { heuristic: 'Differentiate between needs and wants.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_minimalist_design',
        name: 'plugin_heuristic_minimalist_design_name',
        description: 'plugin_heuristic_minimalist_design_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Less, but better (Dieter Rams).', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
            { heuristic: 'Subtract until it breaks.', confidence: 0.88, effectivenessScore: 0.85, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_resilience',
        name: 'plugin_heuristic_resilience_name',
        description: 'plugin_heuristic_resilience_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Focus on your locus of control.', confidence: 0.95, effectivenessScore: 0.92, validationStatus: 'validated' },
            { heuristic: 'View setbacks as learning opportunities.', confidence: 0.9, effectivenessScore: 0.88, validationStatus: 'validated' },
        ],
    },
    {
        id: 'heuristic_strategic_foresight',
        name: 'plugin_heuristic_strategic_foresight_name',
        description: 'plugin_heuristic_strategic_foresight_desc',
        type: 'HEURISTIC',
        status: 'enabled',
        defaultStatus: 'enabled',
        heuristics: [
            { heuristic: 'Identify weak signals that could become future trends.', confidence: 0.85, effectivenessScore: 0.8, validationStatus: 'validated' },
            { heuristic: 'Think in terms of probabilities, not certainties.', confidence: 0.95, effectivenessScore: 0.9, validationStatus: 'validated' },
        ],
    },
];
