// state/knowledge/philosophyOfMind.ts
import { KnowledgeFact } from '../../types';

export const philosophyOfMindKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  { subject: 'Qualia', predicate: 'are', object: 'subjective, qualitative properties of experiences', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Qualia', predicate: 'represent', object: 'the "what it is like" character of mental states', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Hard Problem of Consciousness', predicate: 'is the problem of explaining', object: 'why and how we have qualia', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'David Chalmers', predicate: 'formulated', object: 'The Hard Problem of Consciousness', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Mind-body problem', predicate: 'concerns', object: 'the relationship between thought and consciousness in the human mind, and the brain as part of the physical body', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Dualism', predicate: 'is a philosophical view that', object: 'mental phenomena are, in some respects, non-physical', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'René Descartes', predicate: 'is associated with', object: 'Cartesian Dualism', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Physicalism', predicate: 'is a philosophical view that', object: 'everything which exists is no more extensive than its physical properties', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Functionalism', predicate: 'is a theory that', object: 'mental states are constituted solely by their functional role', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Functionalism', predicate: 'implies that', object: 'consciousness can be implemented on non-biological systems', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Epistemology', predicate: 'is the branch of philosophy concerned with', object: 'the theory of knowledge', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Epistemology', predicate: 'studies', object: 'the nature, origin, and scope of knowledge', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Intentionality', predicate: 'is the power of minds to be', object: 'about, to represent, or to stand for, things, properties and states of affairs', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Chinese Room Argument', predicate: 'is a thought experiment by', object: 'John Searle', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Chinese Room Argument', predicate: 'challenges', object: 'the view that digital computers can have a mind or consciousness', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Panpsychism', predicate: 'is the view that', object: 'consciousness, mind, or soul is a universal and primordial feature of all things', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Eliminative Materialism', predicate: 'is the claim that', object: 'people\'s common-sense understanding of the mind (or folk psychology) is false', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Patricia Churchland', predicate: 'is a prominent advocate for', object: 'Eliminative Materialism', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Embodied Cognition', predicate: 'is the theory that', object: 'many features of cognition are shaped by aspects of the entire body of the organism', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Extended Mind Thesis', predicate: 'claims that', object: 'the mind is not located entirely inside the head, but extends into the external world', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Andy Clark and David Chalmers', predicate: 'proposed the', object: 'Extended Mind Thesis', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Turing Test', predicate: 'was developed by', object: 'Alan Turing', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Turing Test', predicate: 'is a test of a machine\'s ability to', object: 'exhibit intelligent behavior equivalent to, or indistinguishable from, that of a human', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Idealism', predicate: 'is the group of philosophies which assert that', object: 'reality is fundamentally mental or otherwise immaterial', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Materialism', predicate: 'is a form of', object: 'Physicalism', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Daniel Dennett', predicate: 'is a philosopher who', object: 'argues against the concept of qualia', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'The concept of "Self"', predicate: 'is a central topic in', object: 'philosophy of mind', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Solipsism', predicate: 'is the philosophical idea that', object: 'only one\'s own mind is sure to exist', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Reductionism', predicate: 'in philosophy of mind is the view that', object: 'mental states can be fully explained by lower-level physical processes', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Emergentism', predicate: 'in philosophy of mind is the view that', object: 'the mind is an emergent property of complex brain activity', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
];