// state/knowledge/probabilityTheory.ts
import { KnowledgeFact } from '../../types';

export const probabilityTheoryKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  // --- Large Deviations Theory (LDT) ---
  { subject: 'Large Deviations Theory', predicate: 'is a branch of', object: 'probability theory', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'definition' },
  { subject: 'Large Deviations Theory', predicate: 'concerns the', object: 'asymptotic behavior of remote tails of sequences of probability distributions', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Large Deviations Theory', predicate: 'quantifies the', object: 'exponential decay of probabilities of certain rare events', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Large Deviation Principle (LDP)', predicate: 'is a central concept in', object: 'Large Deviations Theory', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'definition' },
  { subject: 'Large Deviation Principle', predicate: 'characterizes', object: 'probabilities of rare events on an exponential scale', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Rate function', predicate: 'is a key component of the', object: 'Large Deviation Principle', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'definition' },
  { subject: 'Rate function', predicate: 'measures the', object: 'exponential rate of decay of the probability of a rare event', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A good rate function', predicate: 'is', object: 'non-negative and lower semi-continuous', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'The minimum of a rate function', predicate: 'is typically', object: 'zero', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'The zero of a rate function', predicate: 'corresponds to the', object: 'most probable event or limit', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Cramér\'s theorem', predicate: 'is a fundamental result in', object: 'Large Deviations Theory', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'theorem' },
  { subject: 'Cramér\'s theorem', predicate: 'establishes the LDP for', object: 'the sample mean of i.i.d. real-valued random variables', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Harald Cramér', predicate: 'is a pioneer in the field of', object: 'Large Deviations Theory', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Sanov\'s theorem', predicate: 'establishes the LDP for the', object: 'empirical measure of a sequence of i.i.d. random variables', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'theorem' },
  { subject: 'Sanov\'s theorem', predicate: 'uses', object: 'relative entropy (Kullback–Leibler divergence) as the rate function', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Schilder\'s theorem', predicate: 'establishes the LDP for', object: 'Brownian motion in the space of continuous functions', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'theorem' },
  { subject: 'Contraction principle', predicate: 'is a tool in LDT for', object: 'deriving a LDP for a function of a sequence that already has one', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Varadhan\'s lemma', predicate: 'is used to', object: 'approximate integrals with respect to a family of measures satisfying a LDP', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'S.R. Srinivasa Varadhan', predicate: 'was awarded the Abel Prize for his work on', object: 'Large Deviations Theory', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'LDT applications', predicate: 'include', object: 'statistical mechanics', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'LDT applications', predicate: 'include', object: 'information theory', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'LDT applications', predicate: 'include', object: 'risk management and finance', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'LDT applications', predicate: 'include', object: 'queuing theory', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'In statistical mechanics, LDT', predicate: 'provides a framework for understanding', object: 'entropy and the emergence of macroscopic laws', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'In information theory, LDT', predicate: 'is related to', object: 'the method of types and error exponents in channel coding', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  
  // --- Theory of Rare Events in Statistics ---
  { subject: 'Rare event', predicate: 'in statistics is an', object: 'event with a low probability of occurrence', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'definition' },
  { subject: 'Studying rare events', predicate: 'is important for', object: 'risk assessment and reliability engineering', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Heavy-tailed distributions', predicate: 'are probability distributions whose', object: 'tails are not exponentially bounded', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'definition' },
  { subject: 'Heavy-tailed distributions', predicate: 'are prone to producing', object: 'extreme events (outliers) more frequently than light-tailed distributions', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Light-tailed distributions', predicate: 'like the Normal distribution, have', object: 'probabilities of extreme events that decay exponentially fast', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Importance sampling', predicate: 'is a Monte Carlo method for', object: 'estimating properties of a particular distribution, while only having samples generated from a different distribution', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Importance sampling', predicate: 'is a common technique for', object: 'rare event simulation', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'In rare event simulation, importance sampling', predicate: 'works by', object: 'biasing the distribution to make the rare event more likely to occur', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Cross-entropy method', predicate: 'is an adaptive version of', object: 'importance sampling for rare event simulation', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Markov chain Monte Carlo (MCMC)', predicate: 'methods can be used to', object: 'simulate rare events in complex systems', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Catastrophe theory', predicate: 'studies', object: 'how small, continuous changes in parameters can cause abrupt, discontinuous shifts in system behavior', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Financial market crashes', predicate: 'are examples of', object: 'rare events studied in statistics', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Insurance claims for natural disasters', predicate: 'are modeled using', object: 'rare event analysis', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'System failures in engineering', predicate: 'are often analyzed as', object: 'rare events', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Poisson distribution', predicate: 'is often used to model the', object: 'number of times an event occurred in a given interval of time or space', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'For rare events, the Poisson distribution', predicate: 'can be a', object: 'good approximation for the binomial distribution', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Chernoff bound', predicate: 'gives exponentially decreasing bounds on', object: 'tail probabilities of sums of independent random variables', confidence: 0.95, strength: 1.0, lastAccessed: 0 },

  // --- Theory of Rare Events in Quantum Mechanics ---
  { subject: 'Quantum tunneling', predicate: 'is a', object: 'quantum mechanical phenomenon where a particle tunnels through a barrier that it classically cannot surmount', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Quantum tunneling', predicate: 'is an example of a', object: 'rare quantum event', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'The probability of quantum tunneling', predicate: 'depends exponentially on the', object: 'thickness and height of the barrier', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Alpha decay', predicate: 'is a nuclear process explained by', object: 'quantum tunneling', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Scanning Tunneling Microscopes (STMs)', predicate: 'operate based on', object: 'quantum tunneling', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'An instanton', predicate: 'in quantum field theory is a', object: 'classical solution to the equations of motion with a finite, non-zero action in Euclidean spacetime', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Instantons', predicate: 'describe', object: 'tunneling events between different vacua of a quantum field theory', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'False vacuum decay', predicate: 'is a hypothetical process where', object: 'a region of a metastable vacuum state tunnels into a more stable state', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'False vacuum decay', predicate: 'is an example of a', object: 'catastrophic rare event in cosmology', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'The WKB approximation', predicate: 'is a method for finding', object: 'approximate solutions to linear differential equations with spatially varying coefficients', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'The WKB approximation', predicate: 'can be used to calculate', object: 'tunneling probabilities in quantum mechanics', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Large deviations theory', predicate: 'provides a mathematical framework for', object: 'understanding instantons and quantum tunneling', confidence: 0.85, strength: 1.0, lastAccessed: 0 },
  { subject: 'Quantum fluctuations', predicate: 'can lead to', object: 'brief, rare appearances of virtual particles', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Casimir effect', predicate: 'is a result of', object: 'quantum vacuum fluctuations', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Hawking radiation', predicate: 'is a theoretical prediction where', object: 'black holes emit radiation due to quantum effects near the event horizon', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Hawking radiation', predicate: 'can be viewed as a', object: 'tunneling process for particle-antiparticle pairs', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Quantum Zeno effect', predicate: 'is a situation in which', object: 'an unstable quantum system, if observed continuously, will never decay', confidence: 0.95, strength: 1.0, lastAccessed: 0 },

  // --- Extreme Value Theory (EVT) ---
  { subject: 'Extreme Value Theory (EVT)', predicate: 'is a branch of', object: 'statistics', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'definition' },
  { subject: 'Extreme Value Theory', predicate: 'deals with the', object: 'extreme deviations from the median of probability distributions', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'EVT', predicate: 'seeks to predict the', object: 'probability of events that are more extreme than any previously observed', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Fisher–Tippett–Gnedenko theorem', predicate: 'is a central result in', object: 'Extreme Value Theory', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'theorem' },
  { subject: 'Fisher–Tippett–Gnedenko theorem', predicate: 'states that the distribution of the maximum of a large number of i.i.d. random variables can only converge to', object: 'one of three types of distributions', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The three extreme value distributions', predicate: 'are', object: 'Gumbel, Fréchet, and Weibull', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Generalized Extreme Value (GEV) distribution', predicate: 'combines the', object: 'Gumbel, Fréchet, and Weibull distributions into a single family', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The GEV distribution', predicate: 'is characterized by a', object: 'shape parameter (ξ)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Gumbel distribution', predicate: 'corresponds to a GEV shape parameter of', object: 'ξ = 0', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Fréchet distribution', predicate: 'corresponds to a GEV shape parameter of', object: 'ξ > 0', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Weibull distribution', predicate: 'corresponds to a GEV shape parameter of', object: 'ξ < 0', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Fréchet distributions', predicate: 'are heavy-tailed, describing', object: 'extreme financial events like market crashes', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Gumbel distributions', predicate: 'are used for modeling', object: 'maximums of light-tailed distributions, like rainfall', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Weibull distributions', predicate: 'have a finite upper bound, used for modeling', object: 'events like wind speed or material strength', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Block Maxima', predicate: 'is a method in EVT that involves', object: 'dividing data into blocks and fitting the GEV distribution to the maximums of each block', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Peaks Over Threshold (POT)', predicate: 'is a method in EVT that involves', object: 'analyzing data points that exceed a certain high threshold', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Pickands–Balkema–de Haan theorem', predicate: 'is the theoretical basis for the', object: 'Peaks Over Threshold method', confidence: 1, strength: 1.0, lastAccessed: 0, type: 'theorem' },
  { subject: 'Pickands–Balkema–de Haan theorem', predicate: 'states that for a large class of distributions, the distribution of excesses over a high threshold is well-approximated by the', object: 'Generalized Pareto Distribution (GPD)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Generalized Pareto Distribution (GPD)', predicate: 'is used in the', object: 'Peaks Over Threshold (POT) approach', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The choice of threshold', predicate: 'is a critical and difficult step in the', object: 'Peaks Over Threshold (POT) method', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Return level', predicate: 'is a concept in EVT that describes the', object: 'level expected to be exceeded on average once every M periods', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A 100-year flood', predicate: 'is an example of a', object: 'return level', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A 100-year flood', predicate: 'has a', object: '1% chance of being exceeded in any given year', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'EVT applications', predicate: 'include', object: 'hydrology (modeling extreme floods)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'EVT applications', predicate: 'include', object: 'finance (calculating Value at Risk)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'EVT applications', predicate: 'include', object: 'structural engineering (designing for extreme wind or wave loads)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'EVT applications', predicate: 'include', object: 'meteorology (predicting extreme weather events)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'EVT applications', predicate: 'include', object: 'telecommunications (modeling network traffic bursts)', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Value at Risk (VaR)', predicate: 'is a measure of', object: 'the risk of loss for investments', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'EVT', predicate: 'can provide more accurate estimates of', object: 'Value at Risk (VaR) than traditional methods', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'The tail index', predicate: 'is a parameter that describes the', object: 'heaviness of the tail of a distribution', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Hill estimator', predicate: 'is a method for estimating the', object: 'tail index', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'EVT assumes', predicate: 'that the extreme events are', object: 'independent and identically distributed (i.i.d.)', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Extremal index', predicate: 'is a measure used to', object: 'account for short-range dependence (clustering) of extremes', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'A low extremal index (less than 1)', predicate: 'indicates that', object: 'extreme events tend to occur in clusters', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Multivariate Extreme Value Theory', predicate: 'deals with the', object: 'joint behavior of extremes of multiple variables', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Copulas', predicate: 'are used in', object: 'Multivariate Extreme Value Theory to model dependence structure', confidence: 0.9, strength: 1.0, lastAccessed: 0 }
];