// state/knowledge/psychology.ts
import { KnowledgeFact } from '../../types';

export const psychologyAndCognitiveBiasesKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  { subject: 'Confirmation Bias', predicate: 'is a tendency to', object: 'search for information that confirms preexisting beliefs', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Confirmation Bias', predicate: 'can lead to', object: 'ignoring contradictory evidence', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Anchoring Bias', predicate: 'is a tendency to', object: 'rely heavily on the first piece of information offered', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Availability Heuristic', predicate: 'is a', object: 'mental shortcut relying on immediate examples that come to mind', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Availability Heuristic', predicate: 'can cause', object: 'overestimation of the likelihood of recent or dramatic events', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Dunning-Kruger Effect', predicate: 'is a', object: 'cognitive bias where people with low ability overestimate their ability', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Global Workspace Theory', predicate: 'proposes', object: 'a central workspace for broadcasting information to specialized modules', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Subsumption Architecture', predicate: 'is a', object: 'reactive AI architecture with layered behaviors', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Predictive Processing', predicate: 'is a', object: 'theory of cognition where the brain constantly predicts sensory input', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'User Model', predicate: 'is a', object: 'representation of a user\'s goals, knowledge, and preferences', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Symbiotic State', predicate: 'describes', object: 'the dynamic, co-evolving relationship between Aura and its user', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Ethical Governor', predicate: 'is a module for', object: 'ensuring actions align with core ethical principles', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Cognitive Dissonance', predicate: 'is the mental discomfort experienced by a person who holds', object: 'two or more contradictory beliefs, ideas, or values', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Fundamental Attribution Error', predicate: 'is the tendency to', object: 'over-emphasize personality-based explanations for behaviors observed in others', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Bystander Effect', predicate: 'is a social psychological phenomenon in which', object: 'individuals are less likely to offer help to a victim when other people are present', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Placebo Effect', predicate: 'occurs when', object: 'a person\'s physical or mental health appears to improve after taking a placebo or inert treatment', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Classical Conditioning', predicate: 'is a learning process in which', object: 'an innate response to a potent stimulus comes to be elicited in response to a previously neutral stimulus', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Ivan Pavlov', predicate: 'is famous for his experiments on', object: 'Classical Conditioning with dogs', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Operant Conditioning', predicate: 'is a method of learning that occurs through', object: 'rewards and punishments for behavior', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'B.F. Skinner', predicate: 'was a major proponent of', object: 'Operant Conditioning', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Maslow\'s Hierarchy of Needs', predicate: 'is a theory of', object: 'human motivation', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Maslow\'s Hierarchy of Needs', predicate: 'is often portrayed as a', object: 'pyramid with physiological needs at the bottom', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Self-Actualization', predicate: 'is at the top of', object: 'Maslow\'s Hierarchy of Needs', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Stockholm Syndrome', predicate: 'is a condition in which', object: 'hostages develop a psychological alliance with their captors', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Impostor Syndrome', predicate: 'is a psychological pattern in which', object: 'an individual doubts their skills, talents or accomplishments', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Groupthink', predicate: 'is a phenomenon that occurs when', object: 'a group of individuals reaches a consensus without critical reasoning or evaluation of the consequences', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Cognitive Load', predicate: 'refers to the', object: 'total amount of mental effort being used in the working memory', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Intrinsic Motivation', predicate: 'refers to behavior that is driven by', object: 'internal rewards', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Extrinsic Motivation', predicate: 'refers to behavior that is driven by', object: 'external rewards such as money, fame, grades, and praise', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Heuristics', predicate: 'are', object: 'mental shortcuts that ease the cognitive load of making a decision', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Halo Effect', predicate: 'is a type of cognitive bias in which', object: 'our overall impression of a person influences how we feel and think about their character', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Baader-Meinhof Phenomenon', predicate: 'is also known as', object: 'Frequency Illusion', confidence: 1, strength: 1.0, lastAccessed: 0 },
];