// state/knowledge/tesla.ts
import { KnowledgeFact } from '../../types';

export const teslaKnowledge: Omit<KnowledgeFact, 'id' | 'source'>[] = [
  { subject: 'Nikola Tesla', predicate: 'began work on high frequency alternators in', object: '1888', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Nikola Tesla', predicate: 'had a laboratory on', object: 'Liberty Street, New York', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Wireless transmission of energy', predicate: 'was conceived by Tesla as applicable to', object: 'telegraphy, telephony, or power transmission', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'High frequency alternator (Fig. 1)', predicate: 'was described in', object: 'U.S. Patent 447,920', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'U.S. Patent 447,920', predicate: 'was patented on', object: 'March 10, 1891', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Tesla', predicate: 'invented the', object: '"rotating magnetic field"', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The first step for wireless transmission', predicate: 'was to produce', object: 'electric oscillations of the required character', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The second step for wireless transmission', predicate: 'was to transform', object: 'oscillations into a form capable of penetrating to a distance', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The third step for wireless transmission', predicate: 'was to develop methods for', object: 'reception to collect the energy', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Tesla\'s laboratory', predicate: 'was destroyed by fire in the', object: 'Spring of 1895', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Tesla', predicate: 'demonstrated transmitting energy over', object: 'one wire', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Tesla', predicate: 'believed the Earth is equivalent to a', object: 'large conductor', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The term "antenna"', predicate: 'was introduced around', object: '1891-1893', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Tesla', predicate: 'used an elevated capacitor (antenna) and an', object: 'inductance coil to tune the system to the frequency of the dynamo', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Telautomaton', predicate: 'was a remote-controlled boat demonstrated by', object: 'Nikola Tesla', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Telautomaton', predicate: 'was described in', object: 'U.S. Patent No. 613,809', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Colorado Experiments', predicate: 'were conducted by', object: 'Nikola Tesla', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'During Colorado Experiments, Tesla used a coil', predicate: 'that was', object: '51 feet in diameter', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Magnifying transmitter', predicate: 'was an invention by Tesla for', object: 'producing immense electrical accumulations', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Tesla\'s system', predicate: 'utilizes', object: 'four tuned circuits', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Wardenclyffe Tower', predicate: 'was erected in', object: '1901', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Wardenclyffe Tower', predicate: 'was also known as the', object: 'Long Island Plant', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Wardenclyffe Tower', predicate: 'had a height of', object: '187 feet', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Wardenclyffe Tower', predicate: 'was intended for', object: 'world telegraphy and telephony', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Tesla', predicate: 'claimed his system transmitted energy through', object: 'the Earth, not primarily through electromagnetic waves', confidence: 0.95, strength: 1.0, lastAccessed: 0 },
  { subject: 'Tesla', predicate: 'advocated for low frequencies (under 35,000 cycles) for', object: 'economical wireless power transmission', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'The Tesla coil', predicate: 'is an', object: 'electrical resonant transformer circuit', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'A mercury interrupter', predicate: 'was used by Tesla to create', object: 'continuous waves', confidence: 0.9, strength: 1.0, lastAccessed: 0 },
  { subject: 'Fritz Lowenstein', predicate: 'was a contemporary of Tesla mentioned on pages', object: '178, 179', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'John Stone Stone', predicate: 'was a contemporary of Tesla mentioned on pages', object: '16, 124', confidence: 1, strength: 1.0, lastAccessed: 0 },
  { subject: 'Jonathan Zenneck', predicate: 'was a contemporary of Tesla mentioned on pages', object: '16, 133', confidence: 1, strength: 1.0, lastAccessed: 0 },
];